// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGetAllDictionaryItemsData, GetGetAllDictionaryItemsResponses, GetGetAllViewsData, GetGetAllViewsResponses, GetGetApiEndpointData, GetGetApiEndpointResponses, GetGetApiKeyData, GetGetApiKeyResponses, GetGetApiRegionData, GetGetApiRegionResponses, GetGetPreviewByIdData, GetGetPreviewByIdResponses, GetGetTranslateSettingData, GetGetTranslateSettingResponses, GetGetTranslatorSettingData, GetGetTranslatorSettingResponses, GetGetViewByIdData, GetGetViewByIdResponses, GetTranslateDictionaryItemByIdData, GetTranslateDictionaryItemByIdResponses, PostAddExistingDictionaryItemData, PostAddExistingDictionaryItemResponses, PostAddNewDictionaryItemData, PostAddNewDictionaryItemResponses, PostPreviewAddExistingDictionaryItemData, PostPreviewAddExistingDictionaryItemResponses, PostPreviewAddNewDictionaryItemData, PostPreviewAddNewDictionaryItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AutoDictionariesService {
    public static postAddExistingDictionaryItem<ThrowOnError extends boolean = false>(options?: Options<PostAddExistingDictionaryItemData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAddExistingDictionaryItemResponses, unknown, ThrowOnError>({
            url: '/add-existing-dictionary-item',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static postAddNewDictionaryItem<ThrowOnError extends boolean = false>(options?: Options<PostAddNewDictionaryItemData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAddNewDictionaryItemResponses, unknown, ThrowOnError>({
            url: '/add-new-dictionary-item',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getGetAllDictionaryItems<ThrowOnError extends boolean = false>(options?: Options<GetGetAllDictionaryItemsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetAllDictionaryItemsResponses, unknown, ThrowOnError>({
            url: '/get-all-dictionary-items',
            ...options
        });
    }
    
    public static getGetAllViews<ThrowOnError extends boolean = false>(options?: Options<GetGetAllViewsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetAllViewsResponses, unknown, ThrowOnError>({
            url: '/get-all-views',
            ...options
        });
    }
    
    public static getGetApiEndpoint<ThrowOnError extends boolean = false>(options?: Options<GetGetApiEndpointData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetApiEndpointResponses, unknown, ThrowOnError>({
            url: '/get-api-endpoint',
            ...options
        });
    }
    
    public static getGetApiKey<ThrowOnError extends boolean = false>(options?: Options<GetGetApiKeyData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetApiKeyResponses, unknown, ThrowOnError>({
            url: '/get-api-key',
            ...options
        });
    }
    
    public static getGetApiRegion<ThrowOnError extends boolean = false>(options?: Options<GetGetApiRegionData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetApiRegionResponses, unknown, ThrowOnError>({
            url: '/get-api-region',
            ...options
        });
    }
    
    public static getGetPreviewById<ThrowOnError extends boolean = false>(options: Options<GetGetPreviewByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetGetPreviewByIdResponses, unknown, ThrowOnError>({
            url: '/get-preview/{id}',
            ...options
        });
    }
    
    public static getGetTranslateSetting<ThrowOnError extends boolean = false>(options?: Options<GetGetTranslateSettingData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetTranslateSettingResponses, unknown, ThrowOnError>({
            url: '/get-translate-setting',
            ...options
        });
    }
    
    public static getGetTranslatorSetting<ThrowOnError extends boolean = false>(options?: Options<GetGetTranslatorSettingData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGetTranslatorSettingResponses, unknown, ThrowOnError>({
            url: '/get-translator-setting',
            ...options
        });
    }
    
    public static getGetViewById<ThrowOnError extends boolean = false>(options: Options<GetGetViewByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetGetViewByIdResponses, unknown, ThrowOnError>({
            url: '/get-view/{id}',
            ...options
        });
    }
    
    public static postPreviewAddExistingDictionaryItem<ThrowOnError extends boolean = false>(options?: Options<PostPreviewAddExistingDictionaryItemData, ThrowOnError>) {
        return (options?.client ?? client).post<PostPreviewAddExistingDictionaryItemResponses, unknown, ThrowOnError>({
            url: '/preview-add-existing-dictionary-item',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static postPreviewAddNewDictionaryItem<ThrowOnError extends boolean = false>(options?: Options<PostPreviewAddNewDictionaryItemData, ThrowOnError>) {
        return (options?.client ?? client).post<PostPreviewAddNewDictionaryItemResponses, unknown, ThrowOnError>({
            url: '/preview-add-new-dictionary-item',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getTranslateDictionaryItemById<ThrowOnError extends boolean = false>(options: Options<GetTranslateDictionaryItemByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetTranslateDictionaryItemByIdResponses, unknown, ThrowOnError>({
            url: '/translate-dictionary-item/{id}',
            ...options
        });
    }
}
