// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44360' | (string & {});
};

export type AddExistingDictionaryItemToViewDto = {
    autoDictionariesModel: AutoDictionariesModel;
    dictionaryKey: string;
    staticContent: string;
};

export type AddNewDictionaryItemToViewDto = {
    tanslate: boolean;
    autoDictionariesModel: AutoDictionariesModel;
    staticContent: StaticContentDto;
};

export type AutoDictionariesModel = {
    id: number;
    key: string;
    alias: string;
    name: string;
    type: string;
    path: string;
    content: string;
    dictionaries?: Array<DictionaryModel> | null;
    staticContent?: Array<StaticContentModel> | null;
    matchDictionaries: number;
};

export type DictionaryModel = {
    key: string;
    id: number;
    guid: string;
    used: number;
    translations: Array<string>;
    translated: boolean;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type FlagModel = {
    alias: string;
};

export type NamedEntityTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    flags: Array<FlagModel>;
    name: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<NamedEntityTreeItemResponseModel>;
};

export type PreviewAddNewDictionaryItemToViewDto = {
    autoDictionariesModel: AutoDictionariesModel;
    staticContent: Array<StaticContentDto>;
};

export type ReferenceByIdModel = {
    id: string;
};

export type StaticContentDto = {
    staticContent: string;
    safeAlias: string;
    parent: string;
};

export type StaticContentModel = {
    used: number;
    staticContent: string;
    dictionary: DictionaryModel;
};

export type PostAddExistingDictionaryItemData = {
    body?: AddExistingDictionaryItemToViewDto;
    path?: never;
    query?: never;
    url: '/add-existing-dictionary-item';
};

export type PostAddExistingDictionaryItemResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostAddExistingDictionaryItemResponse = PostAddExistingDictionaryItemResponses[keyof PostAddExistingDictionaryItemResponses];

export type PostAddNewDictionaryItemData = {
    body?: AddNewDictionaryItemToViewDto;
    path?: never;
    query?: never;
    url: '/add-new-dictionary-item';
};

export type PostAddNewDictionaryItemResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostAddNewDictionaryItemResponse = PostAddNewDictionaryItemResponses[keyof PostAddNewDictionaryItemResponses];

export type GetChildrenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Children';
};

export type GetChildrenResponses = {
    /**
     * OK
     */
    200: PagedNamedEntityTreeItemResponseModel;
};

export type GetChildrenResponse = GetChildrenResponses[keyof GetChildrenResponses];

export type GetGetAllDictionaryItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-all-dictionary-items';
};

export type GetGetAllDictionaryItemsResponses = {
    /**
     * OK
     */
    200: Array<DictionaryModel>;
};

export type GetGetAllDictionaryItemsResponse = GetGetAllDictionaryItemsResponses[keyof GetGetAllDictionaryItemsResponses];

export type GetGetAllViewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-all-views';
};

export type GetGetAllViewsResponses = {
    /**
     * OK
     */
    200: Array<AutoDictionariesModel>;
};

export type GetGetAllViewsResponse = GetGetAllViewsResponses[keyof GetGetAllViewsResponses];

export type GetGetApiEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-api-endpoint';
};

export type GetGetApiEndpointResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGetApiEndpointResponse = GetGetApiEndpointResponses[keyof GetGetApiEndpointResponses];

export type GetGetApiKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-api-key';
};

export type GetGetApiKeyResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGetApiKeyResponse = GetGetApiKeyResponses[keyof GetGetApiKeyResponses];

export type GetGetApiRegionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-api-region';
};

export type GetGetApiRegionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGetApiRegionResponse = GetGetApiRegionResponses[keyof GetGetApiRegionResponses];

export type GetGetPreviewByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/get-preview/{id}';
};

export type GetGetPreviewByIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGetPreviewByIdResponse = GetGetPreviewByIdResponses[keyof GetGetPreviewByIdResponses];

export type GetGetTranslateSettingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-translate-setting';
};

export type GetGetTranslateSettingResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetGetTranslateSettingResponse = GetGetTranslateSettingResponses[keyof GetGetTranslateSettingResponses];

export type GetGetTranslatorSettingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-translator-setting';
};

export type GetGetTranslatorSettingResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGetTranslatorSettingResponse = GetGetTranslatorSettingResponses[keyof GetGetTranslatorSettingResponses];

export type GetGetViewByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/get-view/{id}';
};

export type GetGetViewByIdResponses = {
    /**
     * OK
     */
    200: AutoDictionariesModel;
};

export type GetGetViewByIdResponse = GetGetViewByIdResponses[keyof GetGetViewByIdResponses];

export type PostPreviewAddExistingDictionaryItemData = {
    body?: AddExistingDictionaryItemToViewDto;
    path?: never;
    query?: never;
    url: '/preview-add-existing-dictionary-item';
};

export type PostPreviewAddExistingDictionaryItemResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type PostPreviewAddExistingDictionaryItemResponse = PostPreviewAddExistingDictionaryItemResponses[keyof PostPreviewAddExistingDictionaryItemResponses];

export type PostPreviewAddNewDictionaryItemData = {
    body?: PreviewAddNewDictionaryItemToViewDto;
    path?: never;
    query?: never;
    url: '/preview-add-new-dictionary-item';
};

export type PostPreviewAddNewDictionaryItemResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type PostPreviewAddNewDictionaryItemResponse = PostPreviewAddNewDictionaryItemResponses[keyof PostPreviewAddNewDictionaryItemResponses];

export type GetTranslateDictionaryItemByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/translate-dictionary-item/{id}';
};

export type GetTranslateDictionaryItemByIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetTranslateDictionaryItemByIdResponse = GetTranslateDictionaryItemByIdResponses[keyof GetTranslateDictionaryItemByIdResponses];
