<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<Content Update="../appsettings-schema.auto-dictionaries.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
</Project>