name: Release
on:
  release:
    types:
      - published
jobs:
  release_name:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'src/AutoDictionaries/Client/package-lock.json'
      - name: Install frontend dependencies
        run: npm ci
        working-directory: src/AutoDictionaries/Client
      
      - name: Build frontend assets
        run: npm run build
        working-directory: src/AutoDictionaries/Client
      - name: Build project
        run: dotnet build --configuration Release src/AutoDictionaries
      - name: Package files
        run: dotnet pack --configuration Release  src/AutoDictionaries /p:Version=${{github.ref_name}}
      - name: Publish the package
        run: dotnet nuget push src/AutoDictionaries/build/Release/AutoDictionaries.${{github.ref_name}}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PRIVATE_NUGET_KEY }}
