name: Unit testing
on:
  workflow_dispatch:
jobs:
  release_name:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: dotnet test --configuration Release src/AutoDictionaries.Tests
